-- MySQL Script generated by MySQL Workbench
-- 11/22/17 20:21:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Tienda-online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Tienda-online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tienda-online` DEFAULT CHARACTER SET utf8 ;
USE `Tienda-online` ;

-- -----------------------------------------------------
-- Table `Tienda-online`.`Computadoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tienda-online`.`Computadoras` (
  `idComputadoras` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Precio` INT NOT NULL,
  PRIMARY KEY (`idComputadoras`),
  UNIQUE INDEX `idComputadoras_UNIQUE` (`idComputadoras` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tienda-online`.`Celulares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tienda-online`.`Celulares` (
  `idCelulares` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Precio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCelulares`),
  UNIQUE INDEX `idCelulares_UNIQUE` (`idCelulares` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tienda-online`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tienda-online`.`Usuarios` (
  `idUsuarios` INT NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tienda-online`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tienda-online`.`Venta` (
  `idventa` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`idventa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tienda-online`.`Televisores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tienda-online`.`Televisores` (
  `idTelevisores` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Precio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTelevisores`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
